title: "Jie Hu"
name: "Jie Hu"
position: "Associate Professor"
email: "hujiechelsea@xmu.edu.cn"

affiliation: "Xiamen University"

bio: "My research interests include biostatistics, Bayesian inference and statistical computing."

github: "htlbhj"
google_scholar: "https://scholar.google.co.kr/citations?user=kFS6lBEAAAAJ&hl=en"
url: "https://htlbhj.github.io"
